# Generated by Django 6.1.1 on 2026-10-01 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('pan', 'Pan'), ('embutido', 'Embutido'), ('otro', 'Otro')], max_length=20)),
                ('unidades_por_sol', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('promocion_inicio', models.DateField(blank=True, null=True)),
                ('promocion_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cuentas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='cuentas.tienda')),
                ('vendedor_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelevoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevos', to='ventas.turnocaja')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monto_yape', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('con_precio_promocional', models.BooleanField(default=False)),
                ('tipo_comprobante', models.CharField(choices=[('ninguno', 'Sin comprobante'), ('boleta', 'Boleta'), ('factura', 'Factura')], default='ninguno', max_length=10)),
                ('dni_cliente', models.CharField(blank=True, max_length=8)),
                ('ruc_cliente', models.CharField(blank=True, max_length=11)),
                ('razon_social_cliente', models.CharField(blank=True, max_length=150)),
                ('estado_sunat', models.CharField(default='no_aplica', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_edicion', models.DateTimeField(blank=True, null=True)),
                ('monto_original_antes_de_editar', models.JSONField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.producto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='ventas.turnocaja')),
            ],
        ),
    ]
