# Generated by Django 6.1.1 on 2026-10-01 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_alter_usuario_empresa'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock_actual_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='cuentas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='produccion.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.PositiveIntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('panadero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('tienda', models.ForeignKey(limit_choices_to={'es_planta': True}, on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='cuentas.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='MermaPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='produccion.produccionturno')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_por_unidad', models.DecimalField(decimal_places=4, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.insumo')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('planta_tienda', 'Planta a tienda'), ('entre_tiendas', 'Entre tiendas')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_mototaxi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('canastas_confirmadas', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tienda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_recibidos', to='cuentas.tienda')),
                ('tienda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_enviados', to='cuentas.tienda')),
            ],
        ),
    ]
